(cl:in-package lidar_localization-msg)
(cl:export '(HEADER-VAL
          HEADER
          POS_X_STD-VAL
          POS_X_STD
          POS_Y_STD-VAL
          POS_Y_STD
          POS_Z_STD-VAL
          POS_Z_STD
          VEL_X_STD-VAL
          VEL_X_STD
          VEL_Y_STD-VAL
          VEL_Y_STD
          VEL_Z_STD-VAL
          VEL_Z_STD
          ORI_W_STD-VAL
          ORI_W_STD
          ORI_X_STD-VAL
          ORI_X_STD
          ORI_Y_STD-VAL
          ORI_Y_STD
          ORI_Z_STD-VAL
          ORI_Z_STD
          GYRO_BIAS_X_STD-VAL
          GYRO_BIAS_X_STD
          GYRO_BIAS_Y_STD-VAL
          GYRO_BIAS_Y_STD
          GYRO_BIAS_Z_STD-VAL
          GYRO_BIAS_Z_STD
          ACCEL_BIAS_X_STD-VAL
          ACCEL_BIAS_X_STD
          ACCEL_BIAS_Y_STD-VAL
          ACCEL_BIAS_Y_STD
          ACCEL_BIAS_Z_STD-VAL
          ACCEL_BIAS_Z_STD
))