(cl:in-package lidar_localization-msg)
(cl:export '(HEADER-VAL
          HEADER
          DELTA_POS_X_STD-VAL
          DELTA_POS_X_STD
          DELTA_POS_Y_STD-VAL
          DELTA_POS_Y_STD
          DELTA_POS_Z_STD-VAL
          DELTA_POS_Z_STD
          DELTA_VEL_X_STD-VAL
          DELTA_VEL_X_STD
          DELTA_VEL_Y_STD-VAL
          DELTA_VEL_Y_STD
          DELTA_VEL_Z_STD-VAL
          DELTA_VEL_Z_STD
          DELTA_ORI_X_STD-VAL
          DELTA_ORI_X_STD
          DELTA_ORI_Y_STD-VAL
          DELTA_ORI_Y_STD
          DELTA_ORI_Z_STD-VAL
          DELTA_ORI_Z_STD
          GYRO_BIAS_X_STD-VAL
          GYRO_BIAS_X_STD
          GYRO_BIAS_Y_STD-VAL
          GYRO_BIAS_Y_STD
          GYRO_BIAS_Z_STD-VAL
          GYRO_BIAS_Z_STD
          ACCEL_BIAS_X_STD-VAL
          ACCEL_BIAS_X_STD
          ACCEL_BIAS_Y_STD-VAL
          ACCEL_BIAS_Y_STD
          ACCEL_BIAS_Z_STD-VAL
          ACCEL_BIAS_Z_STD
))