# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lidar_localization/EKFStd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class EKFStd(genpy.Message):
  _md5sum = "2e9c1dfcaa6649033a40105a26a0f620"
  _type = "lidar_localization/EKFStd"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# time of ESKF estimation:
Header header

# a. position:
float64 pos_x_std
float64 pos_y_std
float64 pos_z_std

# b. velocity:
float64 vel_x_std
float64 vel_y_std
float64 vel_z_std

# c. orientation:
float64 ori_w_std
float64 ori_x_std
float64 ori_y_std
float64 ori_z_std

# d. gyro. bias:
float64 gyro_bias_x_std
float64 gyro_bias_y_std
float64 gyro_bias_z_std

# e. accel. bias:
float64 accel_bias_x_std
float64 accel_bias_y_std
float64 accel_bias_z_std
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','pos_x_std','pos_y_std','pos_z_std','vel_x_std','vel_y_std','vel_z_std','ori_w_std','ori_x_std','ori_y_std','ori_z_std','gyro_bias_x_std','gyro_bias_y_std','gyro_bias_z_std','accel_bias_x_std','accel_bias_y_std','accel_bias_z_std']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,pos_x_std,pos_y_std,pos_z_std,vel_x_std,vel_y_std,vel_z_std,ori_w_std,ori_x_std,ori_y_std,ori_z_std,gyro_bias_x_std,gyro_bias_y_std,gyro_bias_z_std,accel_bias_x_std,accel_bias_y_std,accel_bias_z_std

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EKFStd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pos_x_std is None:
        self.pos_x_std = 0.
      if self.pos_y_std is None:
        self.pos_y_std = 0.
      if self.pos_z_std is None:
        self.pos_z_std = 0.
      if self.vel_x_std is None:
        self.vel_x_std = 0.
      if self.vel_y_std is None:
        self.vel_y_std = 0.
      if self.vel_z_std is None:
        self.vel_z_std = 0.
      if self.ori_w_std is None:
        self.ori_w_std = 0.
      if self.ori_x_std is None:
        self.ori_x_std = 0.
      if self.ori_y_std is None:
        self.ori_y_std = 0.
      if self.ori_z_std is None:
        self.ori_z_std = 0.
      if self.gyro_bias_x_std is None:
        self.gyro_bias_x_std = 0.
      if self.gyro_bias_y_std is None:
        self.gyro_bias_y_std = 0.
      if self.gyro_bias_z_std is None:
        self.gyro_bias_z_std = 0.
      if self.accel_bias_x_std is None:
        self.accel_bias_x_std = 0.
      if self.accel_bias_y_std is None:
        self.accel_bias_y_std = 0.
      if self.accel_bias_z_std is None:
        self.accel_bias_z_std = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.pos_x_std = 0.
      self.pos_y_std = 0.
      self.pos_z_std = 0.
      self.vel_x_std = 0.
      self.vel_y_std = 0.
      self.vel_z_std = 0.
      self.ori_w_std = 0.
      self.ori_x_std = 0.
      self.ori_y_std = 0.
      self.ori_z_std = 0.
      self.gyro_bias_x_std = 0.
      self.gyro_bias_y_std = 0.
      self.gyro_bias_z_std = 0.
      self.accel_bias_x_std = 0.
      self.accel_bias_y_std = 0.
      self.accel_bias_z_std = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_16d().pack(_x.pos_x_std, _x.pos_y_std, _x.pos_z_std, _x.vel_x_std, _x.vel_y_std, _x.vel_z_std, _x.ori_w_std, _x.ori_x_std, _x.ori_y_std, _x.ori_z_std, _x.gyro_bias_x_std, _x.gyro_bias_y_std, _x.gyro_bias_z_std, _x.accel_bias_x_std, _x.accel_bias_y_std, _x.accel_bias_z_std))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 128
      (_x.pos_x_std, _x.pos_y_std, _x.pos_z_std, _x.vel_x_std, _x.vel_y_std, _x.vel_z_std, _x.ori_w_std, _x.ori_x_std, _x.ori_y_std, _x.ori_z_std, _x.gyro_bias_x_std, _x.gyro_bias_y_std, _x.gyro_bias_z_std, _x.accel_bias_x_std, _x.accel_bias_y_std, _x.accel_bias_z_std,) = _get_struct_16d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_16d().pack(_x.pos_x_std, _x.pos_y_std, _x.pos_z_std, _x.vel_x_std, _x.vel_y_std, _x.vel_z_std, _x.ori_w_std, _x.ori_x_std, _x.ori_y_std, _x.ori_z_std, _x.gyro_bias_x_std, _x.gyro_bias_y_std, _x.gyro_bias_z_std, _x.accel_bias_x_std, _x.accel_bias_y_std, _x.accel_bias_z_std))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 128
      (_x.pos_x_std, _x.pos_y_std, _x.pos_z_std, _x.vel_x_std, _x.vel_y_std, _x.vel_z_std, _x.ori_w_std, _x.ori_x_std, _x.ori_y_std, _x.ori_z_std, _x.gyro_bias_x_std, _x.gyro_bias_y_std, _x.gyro_bias_z_std, _x.accel_bias_x_std, _x.accel_bias_y_std, _x.accel_bias_z_std,) = _get_struct_16d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_16d = None
def _get_struct_16d():
    global _struct_16d
    if _struct_16d is None:
        _struct_16d = struct.Struct("<16d")
    return _struct_16d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
