// Generated by gencpp from file lidar_localization/optimizeMap.msg
// DO NOT EDIT!


#ifndef LIDAR_LOCALIZATION_MESSAGE_OPTIMIZEMAP_H
#define LIDAR_LOCALIZATION_MESSAGE_OPTIMIZEMAP_H

#include <ros/service_traits.h>


#include <lidar_localization/optimizeMapRequest.h>
#include <lidar_localization/optimizeMapResponse.h>


namespace lidar_localization
{

struct optimizeMap
{

typedef optimizeMapRequest Request;
typedef optimizeMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct optimizeMap
} // namespace lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lidar_localization::optimizeMap > {
  static const char* value()
  {
    return "8d9c3b918a0afafe09791ef8d7853918";
  }

  static const char* value(const ::lidar_localization::optimizeMap&) { return value(); }
};

template<>
struct DataType< ::lidar_localization::optimizeMap > {
  static const char* value()
  {
    return "lidar_localization/optimizeMap";
  }

  static const char* value(const ::lidar_localization::optimizeMap&) { return value(); }
};


// service_traits::MD5Sum< ::lidar_localization::optimizeMapRequest> should match
// service_traits::MD5Sum< ::lidar_localization::optimizeMap >
template<>
struct MD5Sum< ::lidar_localization::optimizeMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lidar_localization::optimizeMap >::value();
  }
  static const char* value(const ::lidar_localization::optimizeMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar_localization::optimizeMapRequest> should match
// service_traits::DataType< ::lidar_localization::optimizeMap >
template<>
struct DataType< ::lidar_localization::optimizeMapRequest>
{
  static const char* value()
  {
    return DataType< ::lidar_localization::optimizeMap >::value();
  }
  static const char* value(const ::lidar_localization::optimizeMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lidar_localization::optimizeMapResponse> should match
// service_traits::MD5Sum< ::lidar_localization::optimizeMap >
template<>
struct MD5Sum< ::lidar_localization::optimizeMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lidar_localization::optimizeMap >::value();
  }
  static const char* value(const ::lidar_localization::optimizeMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar_localization::optimizeMapResponse> should match
// service_traits::DataType< ::lidar_localization::optimizeMap >
template<>
struct DataType< ::lidar_localization::optimizeMapResponse>
{
  static const char* value()
  {
    return DataType< ::lidar_localization::optimizeMap >::value();
  }
  static const char* value(const ::lidar_localization::optimizeMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIDAR_LOCALIZATION_MESSAGE_OPTIMIZEMAP_H
