// Generated by gencpp from file lidar_localization/saveMap.msg
// DO NOT EDIT!


#ifndef LIDAR_LOCALIZATION_MESSAGE_SAVEMAP_H
#define LIDAR_LOCALIZATION_MESSAGE_SAVEMAP_H

#include <ros/service_traits.h>


#include <lidar_localization/saveMapRequest.h>
#include <lidar_localization/saveMapResponse.h>


namespace lidar_localization
{

struct saveMap
{

typedef saveMapRequest Request;
typedef saveMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct saveMap
} // namespace lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lidar_localization::saveMap > {
  static const char* value()
  {
    return "8d9c3b918a0afafe09791ef8d7853918";
  }

  static const char* value(const ::lidar_localization::saveMap&) { return value(); }
};

template<>
struct DataType< ::lidar_localization::saveMap > {
  static const char* value()
  {
    return "lidar_localization/saveMap";
  }

  static const char* value(const ::lidar_localization::saveMap&) { return value(); }
};


// service_traits::MD5Sum< ::lidar_localization::saveMapRequest> should match
// service_traits::MD5Sum< ::lidar_localization::saveMap >
template<>
struct MD5Sum< ::lidar_localization::saveMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lidar_localization::saveMap >::value();
  }
  static const char* value(const ::lidar_localization::saveMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar_localization::saveMapRequest> should match
// service_traits::DataType< ::lidar_localization::saveMap >
template<>
struct DataType< ::lidar_localization::saveMapRequest>
{
  static const char* value()
  {
    return DataType< ::lidar_localization::saveMap >::value();
  }
  static const char* value(const ::lidar_localization::saveMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lidar_localization::saveMapResponse> should match
// service_traits::MD5Sum< ::lidar_localization::saveMap >
template<>
struct MD5Sum< ::lidar_localization::saveMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lidar_localization::saveMap >::value();
  }
  static const char* value(const ::lidar_localization::saveMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar_localization::saveMapResponse> should match
// service_traits::DataType< ::lidar_localization::saveMap >
template<>
struct DataType< ::lidar_localization::saveMapResponse>
{
  static const char* value()
  {
    return DataType< ::lidar_localization::saveMap >::value();
  }
  static const char* value(const ::lidar_localization::saveMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIDAR_LOCALIZATION_MESSAGE_SAVEMAP_H
