// Generated by gencpp from file lidar_localization/saveOdometryRequest.msg
// DO NOT EDIT!


#ifndef LIDAR_LOCALIZATION_MESSAGE_SAVEODOMETRYREQUEST_H
#define LIDAR_LOCALIZATION_MESSAGE_SAVEODOMETRYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidar_localization
{
template <class ContainerAllocator>
struct saveOdometryRequest_
{
  typedef saveOdometryRequest_<ContainerAllocator> Type;

  saveOdometryRequest_()
    {
    }
  saveOdometryRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct saveOdometryRequest_

typedef ::lidar_localization::saveOdometryRequest_<std::allocator<void> > saveOdometryRequest;

typedef boost::shared_ptr< ::lidar_localization::saveOdometryRequest > saveOdometryRequestPtr;
typedef boost::shared_ptr< ::lidar_localization::saveOdometryRequest const> saveOdometryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_localization::saveOdometryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace lidar_localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::lidar_localization::saveOdometryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_localization/saveOdometryRequest";
  }

  static const char* value(const ::lidar_localization::saveOdometryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::lidar_localization::saveOdometryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct saveOdometryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_localization::saveOdometryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::lidar_localization::saveOdometryRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_LOCALIZATION_MESSAGE_SAVEODOMETRYREQUEST_H
