// Generated by gencpp from file lidar_localization/saveOdometry.msg
// DO NOT EDIT!


#ifndef LIDAR_LOCALIZATION_MESSAGE_SAVEODOMETRY_H
#define LIDAR_LOCALIZATION_MESSAGE_SAVEODOMETRY_H

#include <ros/service_traits.h>


#include <lidar_localization/saveOdometryRequest.h>
#include <lidar_localization/saveOdometryResponse.h>


namespace lidar_localization
{

struct saveOdometry
{

typedef saveOdometryRequest Request;
typedef saveOdometryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct saveOdometry
} // namespace lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lidar_localization::saveOdometry > {
  static const char* value()
  {
    return "8d9c3b918a0afafe09791ef8d7853918";
  }

  static const char* value(const ::lidar_localization::saveOdometry&) { return value(); }
};

template<>
struct DataType< ::lidar_localization::saveOdometry > {
  static const char* value()
  {
    return "lidar_localization/saveOdometry";
  }

  static const char* value(const ::lidar_localization::saveOdometry&) { return value(); }
};


// service_traits::MD5Sum< ::lidar_localization::saveOdometryRequest> should match
// service_traits::MD5Sum< ::lidar_localization::saveOdometry >
template<>
struct MD5Sum< ::lidar_localization::saveOdometryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lidar_localization::saveOdometry >::value();
  }
  static const char* value(const ::lidar_localization::saveOdometryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar_localization::saveOdometryRequest> should match
// service_traits::DataType< ::lidar_localization::saveOdometry >
template<>
struct DataType< ::lidar_localization::saveOdometryRequest>
{
  static const char* value()
  {
    return DataType< ::lidar_localization::saveOdometry >::value();
  }
  static const char* value(const ::lidar_localization::saveOdometryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lidar_localization::saveOdometryResponse> should match
// service_traits::MD5Sum< ::lidar_localization::saveOdometry >
template<>
struct MD5Sum< ::lidar_localization::saveOdometryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lidar_localization::saveOdometry >::value();
  }
  static const char* value(const ::lidar_localization::saveOdometryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar_localization::saveOdometryResponse> should match
// service_traits::DataType< ::lidar_localization::saveOdometry >
template<>
struct DataType< ::lidar_localization::saveOdometryResponse>
{
  static const char* value()
  {
    return DataType< ::lidar_localization::saveOdometry >::value();
  }
  static const char* value(const ::lidar_localization::saveOdometryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIDAR_LOCALIZATION_MESSAGE_SAVEODOMETRY_H
